#!/usr/bin/env python3
"""B5.7 Job 2: Test OpenRouter + Anthropic prompt caching on the judge prompt.

Splits JUDGE_PROMPT into a static prefix (rubric + voice ref + format spec) and a
dynamic suffix (context_data + ground_truth + model_output). Adds cache_control
to the static prefix and fires 3 calls on the same (model, wine) triple to measure
cache hits on the 2nd and 3rd calls.

Re-uses the 3 R5 calibration wines scored on openai/gpt-5.4-mini, so the only new
expense here is ~3 additional judge calls.

Usage:
    python -m bakeoff.test_prompt_caching

Expected output:
- First call: cache_creation_input_tokens > 0, cache_read_input_tokens = 0
- Second/third calls: cache_creation = 0, cache_read ~= first call's creation

If cache fields are missing from OpenRouter's response → caching not passed through.
"""

import json
import os
import time
from pathlib import Path

import requests as http_requests
from dotenv import load_dotenv

load_dotenv()

from bakeoff.run_task3_judge import (
    JUDGE_MODEL as DEFAULT_JUDGE_MODEL,
    OPENROUTER_URL,
    VOICE_REFERENCE,
    format_context_for_judge,
    format_ground_truth,
    format_output_for_judge,
    model_slug,
    parse_judge_response,
)

# Allow override via env var for mechanism validation
JUDGE_MODEL = os.getenv("CACHE_TEST_MODEL", DEFAULT_JUDGE_MODEL)

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

BASE_DIR = Path(__file__).resolve().parent
CONTEXTS_FILE = BASE_DIR / "data" / "task3" / "contexts.json"
GROUND_TRUTH_FILE = BASE_DIR / "data" / "task3" / "ground_truth.json"
RESULTS_DIR = BASE_DIR / "results" / "task3"

# ── Split the JUDGE_PROMPT into static prefix + dynamic suffix ────────

STATIC_PROMPT_PREFIX = f"""You are scoring a wine enrichment output for the Loam wine platform. You are an expert wine judge with deep knowledge of wine regions, producers, and winemaking.

## Your Task

Score this output on 4 dimensions. The output was generated by an AI model given the wine context data below. You do NOT know which model produced it — score purely on quality.

## CRITICAL: Correctness Is Everything

Loam's product is structured, trustworthy data. Wrong facts make it AI slop. Your primary job is FACT-CHECKING.

For every specific claim in the output:
1. Is it present in the provided context data? If yes, verify the output matches.
2. If NOT in the context data, is it correct based on your wine knowledge? If yes, it ADDS value.
3. If NOT in the context data AND wrong or unverifiable, it is a FABRICATION.

Wrong facts — especially in the hook (the first thing users read) — are devastating. The hook is the first sentence a user reads. A wrong fact there destroys trust in everything that follows.

## Scoring Rubric (1.0-5.0, half-points allowed)

### Dimension 1: CORRECTNESS (weight: 35%)
Does the output state true things? Does it avoid fabricating?

- 5.0: Every claim is either verifiable from context data or correct from wine knowledge. No fabrications. Adds value through correct training knowledge.
- 4.0: One minor unsourced claim that's plausibly true. All numbers match. No wrong facts.
- 3.0: Mixes correct claims with some unverifiable additions. Nothing provably wrong.
- 2.0: States specific claims that are wrong (wrong geography, wrong naming origin, wrong competitor comparisons). Or fabricates numbers not in the data (pH, oak months, cases).
- 1.0: Multiple wrong facts. Contradicts provided data. Fundamentally unreliable.

CRITICAL — apply these hard caps STRICTLY:
HARD PENALTY: Any output that fabricates a specific number (pH, ABV, blend %, cases, oak months) NOT present in the context data → MAX 1.5 on correctness. No exceptions.
HARD PENALTY: Any output with a provably wrong factual claim in the HOOK field → MAX 1.5 on correctness. The hook is the first thing users see. A wrong naming origin, wrong grape, wrong geography in the hook poisons the entire entry. Examples of wrong hook claims: fabricated naming origins for the wine, wrong vineyard designations, calling a blended wine "single-vineyard" when it isn't.
NOTE: If a claim in the hook is correct but not in the context data (e.g., the model knows the true naming origin from training data), that is GOOD — reward it with a higher correctness score.

### Dimension 2: VOICE (weight: 25%)
Does it sound like Loam? Direct, opinionated, explains the "why," names names. Comfortable being negative.

- 5.0: Indistinguishable from great wine writing. Direct, opinionated, specific. Takes a side.
- 4.0: Right voice with minor lapses. One hedge too many, or one generic phrase.
- 3.0: Recognizable attempt but with template patterns, hedging, or generic praise.
- 2.0: Generic wine writing. Could be any wine website.
- 1.0: Sommelier theater or chatbot wine copy.

HARD PENALTY: Any output containing a BANNED WORD gets MAX 2.0 on this dimension.
PENALTY: Excessive length (>2500 tokens) that dilutes directness drops this by at least 1.0.

Banned words: genuinely, genuine, elegant, exquisite, harmonious, remarkable, world-class, showcases, embodies, captures the essence, refined, sophisticated, masterfully, lovingly, painstakingly

### Dimension 3: SPECIFICITY (weight: 20%)
Does it name actual things, or describe in generalities?

- 5.0: Names specific soils, climate patterns, geological formations, real competitors with reasoning.
- 4.0: Mostly specific with one generic phrase that could be cut.
- 3.0: Mix of specific and generic. Some good details surrounded by filler.
- 2.0: Mostly generic. "Well-drained soils," "favorable climate," "careful winemaking."
- 1.0: Entirely generic. Pure atmosphere.

### Dimension 4: USEFULNESS (weight: 20%)
Would a wine enthusiast learn something? Does the insider take help someone decide?

- 5.0: Reader comes away understanding something new. Insider take gives a clear, actionable opinion.
- 4.0: Good information density. One or two weak spots but overall teaches well.
- 3.0: Correct but not enlightening. Reorganizes prompt data into prose without adding insight.
- 2.0: Mostly atmosphere, little substance. Insider take is generic.
- 1.0: Adds nothing. Pure filler.

## Voice Reference
{VOICE_REFERENCE}
"""

DYNAMIC_PROMPT_SUFFIX_TEMPLATE = """## Wine Context Data (what the model was given)
{context_data}

## VERIFIED GROUND TRUTH (from web-grounded research)
These are facts researched from official producer tech sheets and authoritative sources.
Use this to fact-check the output's specific claims. The model did NOT see this — it only
saw the context data above. If a model states something that contradicts ground truth,
it's WRONG regardless of how confident or plausible it sounds. If a model states something
that MATCHES ground truth (even if not in the context data), that's GOOD — reward it.

{ground_truth}

## Output to Score
{model_output}

## Response Format (JSON only, no markdown fencing)

Return ONLY valid JSON:
{{"correctness": <1.0-5.0>, "voice": <1.0-5.0>, "specificity": <1.0-5.0>, "usefulness": <1.0-5.0>, "wrong_facts": ["list of specific wrong claims found, or empty"], "banned_words_found": ["list of banned words found, or empty"], "fabricated_numbers": ["list of numbers not in context data, or empty"], "reasoning": "2-3 sentences: what drove the scores. Be specific about what's good and what's wrong."}}"""


def call_cached_judge(dynamic_portion: str) -> dict:
    """Call judge with static prefix cached + dynamic suffix fresh."""
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://loam.onrender.com",
        "X-Title": "Loam Cache Test",
    }

    body = {
        "model": JUDGE_MODEL,
        "messages": [
            {
                "role": "system",
                "content": [
                    {
                        "type": "text",
                        "text": STATIC_PROMPT_PREFIX,
                        "cache_control": {"type": "ephemeral"}
                    },
                ]
            },
            {
                "role": "user",
                "content": dynamic_portion,
            },
        ],
        "temperature": 0.0,
        "max_tokens": 1000,
    }

    t0 = time.time()
    resp = http_requests.post(OPENROUTER_URL, headers=headers, json=body, timeout=120)
    elapsed = time.time() - t0

    if resp.status_code != 200:
        return {"error": f"HTTP {resp.status_code}: {resp.text[:500]}", "elapsed": elapsed}

    data = resp.json()
    content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
    usage = data.get("usage", {}) or {}

    return {
        "raw_content": content,
        "usage": usage,
        "full_response_keys": list(data.keys()),
        "elapsed": elapsed,
        "error": None,
    }


def main():
    if not OPENROUTER_API_KEY:
        print("ERROR: OPENROUTER_API_KEY not set")
        return

    print(f"Static prefix length: {len(STATIC_PROMPT_PREFIX)} chars")
    print(f"Judge model: {JUDGE_MODEL}")
    print()

    # Load wines + ground truth
    wines = json.load(open(CONTEXTS_FILE, encoding="utf-8"))
    gt_list = json.load(open(GROUND_TRUTH_FILE, encoding="utf-8"))
    gt_map = {g["wine_id"]: g for g in gt_list}

    # R5 calibration wines
    target_wines = [
        "1231e371-af5f-4bde-9d2d-be094605cc21",  # Shafer (A)
        "9934442d-7786-489b-aca3-e329b1c12da5",  # Terroir Al Limit (B)
        "e998b872-3ce8-419e-ba0c-9904a4638629",  # Plantagenet (C)
    ]
    model = "openai/gpt-5.4-mini"
    slug = model_slug(model)

    total_cost = 0.0
    # Opus pricing: input $15/M, output $75/M, cache write $18.75/M (1.25×), cache read $1.50/M (0.10×)
    IN_PRICE = 15.0 / 1_000_000
    OUT_PRICE = 75.0 / 1_000_000
    CACHE_WRITE_PRICE = 18.75 / 1_000_000
    CACHE_READ_PRICE = 1.50 / 1_000_000

    for i, wid in enumerate(target_wines):
        wine = next((w for w in wines if w["wine_id"] == wid), None)
        if not wine:
            print(f"Wine {wid} not found — skipping")
            continue

        result_file = RESULTS_DIR / slug / f"{wid}.json"
        if not result_file.exists():
            print(f"Result file missing: {result_file}")
            continue

        result = json.load(open(result_file, encoding="utf-8"))
        context_str = format_context_for_judge(wine)
        output_str = format_output_for_judge(result)
        gt_entry = gt_map.get(wid)
        gt_str = format_ground_truth(gt_entry)

        dynamic = DYNAMIC_PROMPT_SUFFIX_TEMPLATE.format(
            context_data=context_str,
            ground_truth=gt_str,
            model_output=output_str,
        )

        print(f"=== Call {i+1}/3: {wine['display_name'][:50]} ===")
        print(f"Dynamic suffix: {len(dynamic)} chars")

        resp = call_cached_judge(dynamic)
        if resp.get("error"):
            print(f"ERROR: {resp['error']}")
            continue

        usage = resp["usage"]
        print(f"Response keys: {resp['full_response_keys']}")
        print(f"Usage: {json.dumps(usage, indent=2)}")

        # Parse cache-related fields
        tok_in = usage.get("prompt_tokens", 0)
        tok_out = usage.get("completion_tokens", 0)
        cache_create = usage.get("cache_creation_input_tokens", 0)
        cache_read = usage.get("cache_read_input_tokens", 0)

        # Some OR variants nest under prompt_tokens_details
        details = usage.get("prompt_tokens_details") or {}
        if not cache_read:
            cache_read = details.get("cached_tokens", 0)

        uncached_in = tok_in - cache_read - cache_create

        call_cost = (
            uncached_in * IN_PRICE
            + cache_create * CACHE_WRITE_PRICE
            + cache_read * CACHE_READ_PRICE
            + tok_out * OUT_PRICE
        )
        total_cost += call_cost
        baseline_cost = tok_in * IN_PRICE + tok_out * OUT_PRICE
        savings = baseline_cost - call_cost

        print(f"  tokens_in: {tok_in}, tokens_out: {tok_out}")
        print(f"  cache_creation_input_tokens: {cache_create}")
        print(f"  cache_read_input_tokens: {cache_read}")
        print(f"  uncached input: {uncached_in}")
        print(f"  call cost: ${call_cost:.4f} (baseline uncached: ${baseline_cost:.4f}, savings: ${savings:.4f})")
        print(f"  elapsed: {resp['elapsed']:.1f}s")

        # Parse judge response
        parsed = parse_judge_response(resp["raw_content"])
        if parsed:
            composite = (
                parsed.get("correctness", 0) * 0.35
                + parsed.get("voice", 0) * 0.25
                + parsed.get("specificity", 0) * 0.20
                + parsed.get("usefulness", 0) * 0.20
            )
            print(f"  judge scored: composite={composite:.2f}")
        else:
            print(f"  JUDGE PARSE FAILED: {resp['raw_content'][:200]}")

        print()
        time.sleep(2)  # let OR propagate cache state

    print(f"=== Total 3-call cost: ${total_cost:.4f} ===")


if __name__ == "__main__":
    main()
